version: "3.9"

services:
  dustin:
    image: ghcr.io/dustin129812/landingpage:1.0.0
    networks:
      - traefik-public
    deploy: 
      replicas: 1
      labels: 
        - "traefik.enable=true"
        - "traefik.http.routers.dustin.entrypoints=http"
        - "traefik.http.routers.dustin.rule=Host(dustin.byronrm.com)"
        - "traefik.http.middlewares.dustin-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.dustin.middlewares=dustin-https-redirect"
        - "traefik.http.routers.dustin-secure.entrypoints=https"
        - "traefik.http.routers.dustin-secure.rule=Host(dustin.byronrm.com)"
        - "traefik.http.routers.dustin-secure.tls=true"
        - "traefik.http.routers.dustin-secure.tls.certresolver=http"
        - "traefik.http.routers.dustin-secure.service=dustin"
        - "traefik.http.services.dustin.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"
networks:
  traefik-public:
    external: true